### ISSUE TITLE
Route issues

### ISSUE THREAD

**Issue by Devesh2607** [webdevmatics/storelocator#1]
gettting error:  http://127.0.0.1:8000/api/nearest-shops 500 (Internal Server Error)

![image](https://user-images.githubusercontent.com/29989727/37812499-cf5eadba-2e79-11e8-9e76-6d821b53754d.png)

**Comment by webdevmatics** [comment]
Can you switch to network tab and click on error and send screenshot?

**Comment by Devesh2607** [comment]
![image](https://user-images.githubusercontent.com/29989727/37822141-148af5c2-2e9f-11e8-8769-4e739d2a3173.png)

I have used the source-code on github. It is not displaying the shop name on result panel and markers on map. I have also watched the storelocator playlist on youtube.

**Comment by Devesh2607** [comment]
I have used the source code on github, it is not displaying the shop name in result panel and markers on map and I have watched the storelocator playlist on youtube on your channel.

**Comment by webdevmatics** [comment]
If click on row highlighted red it will open window inside that go to
preview tab, you will know what the problem is. See if you can resolve or
send me error details

**Comment by Devesh2607** [comment]
Getting this error:

"SQLSTATE[42000]: Syntax error or access violation: 1463 Non-grouping field 'distance' is used in HAVING clause (SQL: SELECT *, ( 3959 * acos( cos( radians(42.363211) ) * cos( radians( lat ) ) * cos( radians( lng ) - radians(-105.071875) ) + sin( radians(42.363211) ) * sin( radians(lat) ) ) ) AS distance FROM shops HAVING distance < 200 ORDER BY distance)"

**Comment by webdevmatics** [comment]
Make sure you are using latest version of mysql.

**Comment by Devesh2607** [comment]
mysql I am currently using: mysql  Ver 15.1 Distrib 10.1.29-MariaDB, for Win32 (AMD64)

**Comment by Devesh2607** [comment]
Thanks it works
